import { StarRatingItem } from '../models/catalog.model';

/**
 * Tabla de equivalencias de estrellas y calificaciones a valor decimal (1.0 a 6.0).
 * Extraído de la Tabla 2 oficial de Nemo Group.
 */
export const STAR_RATINGS: readonly StarRatingItem[] = [
  { categoryType: 'NMO.HTL.RTT.APM', code: 'NMO.HTL.RTN.APM', numericValue: 0 },
  { categoryType: 'NMO.HTL.RTT.APR', code: 'NMO.HTL.RTN.1AP', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.APR', code: 'NMO.HTL.RTN.2AP', numericValue: 2 },
  { categoryType: 'NMO.HTL.RTT.APR', code: 'NMO.HTL.RTN.3AP', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.APR', code: 'NMO.HTL.RTN.4AP', numericValue: 4 },
  { categoryType: 'NMO.HTL.RTT.APR', code: 'NMO.HTL.RTN.5AP', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.BNB', code: 'NMO.HTL.RTN.BNB', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.BTQ', code: 'NMO.HTL.RTN.BTQ', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.CMP', code: 'NMO.HTL.RTN.1CM', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.CMP', code: 'NMO.HTL.RTN.2CM', numericValue: 2 },
  { categoryType: 'NMO.HTL.RTT.DMN', code: 'NMO.HTL.RTN.1DM', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.DMN', code: 'NMO.HTL.RTN.2DM', numericValue: 2 },
  { categoryType: 'NMO.HTL.RTT.DMN', code: 'NMO.HTL.RTN.3DM', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.DMN', code: 'NMO.HTL.RTN.4DM', numericValue: 4 },
  { categoryType: 'NMO.HTL.RTT.DMN', code: 'NMO.HTL.RTN.5DM', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.HHS', code: 'NMO.HTL.RTN.HHS', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.HST', code: 'NMO.HTL.RTN.1HS', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.HST', code: 'NMO.HTL.RTN.2HS', numericValue: 2 },
  { categoryType: 'NMO.HTL.RTT.HST', code: 'NMO.HTL.RTN.3HS', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.HST', code: 'NMO.HTL.RTN.4HS', numericValue: 4 },
  { categoryType: 'NMO.HTL.RTT.HST', code: 'NMO.HTL.RTN.5HS', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.KEY', code: 'NMO.HTL.RTN.1KY', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.KEY', code: 'NMO.HTL.RTN.2KY', numericValue: 2 },
  { categoryType: 'NMO.HTL.RTT.KEY', code: 'NMO.HTL.RTN.3KY', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.KEY', code: 'NMO.HTL.RTN.4KY', numericValue: 4 },
  { categoryType: 'NMO.HTL.RTT.KEY', code: 'NMO.HTL.RTN.5KY', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.LDG', code: 'NMO.HTL.RTN.LDG', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.NIN', code: 'NMO.HTL.RTN.0ST', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.PND', code: 'NMO.HTL.RTN.PND', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.PSD', code: 'NMO.HTL.RTN.PSD', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.RES', code: 'NMO.HTL.RTN.RES', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.RLH', code: 'NMO.HTL.RTN.RLH', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.RRL', code: 'NMO.HTL.RTN.1RL', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.RRL', code: 'NMO.HTL.RTN.2RL', numericValue: 2 },
  { categoryType: 'NMO.HTL.RTT.RRL', code: 'NMO.HTL.RTN.3RL', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.RRL', code: 'NMO.HTL.RTN.4RL', numericValue: 4 },
  { categoryType: 'NMO.HTL.RTT.RRL', code: 'NMO.HTL.RTN.5RL', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.STD', code: 'NMO.HTL.RTN.STD', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.1ST', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.15S', numericValue: 1.5 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.2ST', numericValue: 2 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.25S', numericValue: 2.5 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.3ST', numericValue: 3 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.35S', numericValue: 3.5 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.4ST', numericValue: 4 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.45S', numericValue: 4.5 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.4SL', numericValue: 4 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.5ST', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.55S', numericValue: 5.5 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.5SL', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.6ST', numericValue: 6 },
  { categoryType: 'NMO.HTL.RTT.STR', code: 'NMO.HTL.RTN.NNN', numericValue: 5 },
  { categoryType: 'NMO.HTL.RTT.VLL', code: 'NMO.HTL.RTN.VLL', numericValue: 1 },
  { categoryType: 'NMO.HTL.RTT.VTH', code: 'NMO.HTL.RTN.VTH', numericValue: 1 },
];
